import Cookies from 'js-cookie'

const TokenKey = '_lifanli_session'

export function getToken() {
  if (process.env.NODE_ENV === 'development') {
    const token = 'eVVPc0c2b1YvTUpRUEExcUtZN05XekRLYjc5N3U5aG1pZko5d1RSUUpnQ3l1TFE4dnRLQ1NBdEF3WHlIWnMzSjArK3M5WHIyOFFRNFUxOVM1STBNS29TRVlpNTNMVllURXlEcks4Ykh3bGYrVzRlaVRIRXVpb3NWdXBFQng4eGZxUk45ZHhqcXlLNk9SQnZPTUUwT01jRWNseDdPa0JlekQyRmdRc2JwMmRScll2NW0zeGt0bHJwNVp1ejZadzdJYmttL3MrWXI5aW1heUh6VzBlSUIzbFFrQjRnc0NVOWRQVVRITWdKazFCcXE2QjhzZTBkNXlBSWczQVUvRXFzOWM4dWdveHRacVFwak9RL3dwV21kUGtTY2hPZ0xNby9wTExON2w5K0t1czZMWlM0eVBxRWlDZTJJeFcvdXBJQU9PNGhhUzJhNmpoMUgwVW1IOTMvaXNEaE9IZ29UTVAyZHBWTGdWcDJaRlBFZXloaEF2dE1iMk9EY1ZFMXdJZmpVWWlZdWZ2YkUvY2M3YVAzc0RPcjJzMFBUV05RNktVNXVSTXIrNDVMMVkzckNualNETm1tWXNsTFdpbktWRzVmdUs5SXRGOUFaVUUvMWlQQklSeWhJaGdQaDB2M1dpWjJibzVRUlVhUzA2TEhSKzdhc3l4dlhxd2Mxc0RNSkcyVWhoRHZibGIyR2hESDFOZHoycHVtS0dqUWMzV2pYMWJoaFl5UEcyRHkzSlBOWUFsZkpza1doSXZHVjM2SERYM0pTbjNyY0lCNGpoaWsvZjJzQkxXUHBwUT09LS1DUHBXMlFsbndrQkgrNW9ET0h2bDJRPT0=--bd52fd3789ef5e65a624ce0e4f5261638cc817a6'
    Cookies.set(TokenKey, token)
    return Cookies.get(TokenKey)
  } else {
    return true
  }
}

export function setToken(token) {
  return Cookies.set(TokenKey, token)
}

export function removeToken() {
  return Cookies.remove(TokenKey)
}
